sudo: false
language: node_js
node_js:
- '10'
services: mongodb
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - dist
  - .cache
  - bin
before_install:
- npm update
install:
- npm install
script:
- npm run build
- ./scripts/lighthouse.sh
- npm run lint
- npm run test
- npm run coveralls

